version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: sk-db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpbruker
      MYSQL_PASSWORD: abc123x
      MYSQL_ROOT_PASSWORD: abc123x
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: sk-wp
    depends_on:
      - db
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpbruker
      WORDPRESS_DB_PASSWORD: abc123x
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:
